DROP DATABASE IF EXISTS smartshopdb;
CREATE DATABASE smartshopdb;
USE smartshopdb;

CREATE TABLE bloco (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    BLOCO VARCHAR(30) NOT NULL
);

CREATE TABLE apartamento (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    APARTAMENTO INT NOT NULL
);

CREATE TABLE usuario (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ID_BLOCO INT,
    ID_APARTAMENTO INT,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    CPF CHAR(11) NOT NULL UNIQUE,
    TIPO VARCHAR(30) DEFAULT 'CLIENTE',
    SENHA VARCHAR(8),
    ID_SESSAO VARCHAR(255),
    FOREIGN KEY (ID_BLOCO) REFERENCES bloco (ID),
    FOREIGN KEY (ID_APARTAMENTO) REFERENCES apartamento (ID)
);

CREATE TABLE categoria (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE marca (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(100) NOT NULL
);

CREATE TABLE produto (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ID_CATEGORIA INT,
    ID_MARCA INT,
    NOME VARCHAR(255) NOT NULL,
    CODIGO_DE_BARRAS VARCHAR(13) NOT NULL,
    PRECO DECIMAL(4,2) NOT NULL,
    ESTOQUE INT NOT NULL,
    FOREIGN KEY (ID_CATEGORIA) REFERENCES categoria (ID),
    FOREIGN KEY (ID_MARCA) REFERENCES marca (ID)
);

CREATE TABLE forma_pagamento (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    TIPO VARCHAR(255) NOT NULL
);

CREATE TABLE carrinho (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ID_FORMA_PAGAMENTO INT,
    ID_CLIENTE INT,
    DATA_COMPRA DATE NOT NULL,
    TOTAL DECIMAL(7,2) NOT NULL,
    FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES forma_pagamento (ID)
);

CREATE TABLE item (
    ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    ID_CARRINHO INT,
    ID_PRODUTO INT,
    PRECO DECIMAL(6,2) NOT NULL,
    QUANTIDADE INT NOT NULL,
    FOREIGN KEY (ID_CARRINHO) REFERENCES carrinho (ID),
    FOREIGN KEY (ID_PRODUTO) REFERENCES produto (ID)
);
